### ISSUE TITLE
Add support for JSON output to stdout

### ISSUE THREAD

**Issue by scottslowe** [google/gke-policy-automation#129]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do
not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

It would be useful to have a flag or command-line parameter that would allow the `gke-policy` tool to stream JSON to STDOUT. Currently the only JSON support is writing to a JSON file. Streaming to STDOUT would allow for integration with other command-line tools such as `jq`.

### References

* No relevant/known issues or PRs

**Comment by danielmarzini** [comment]
Thanks @scottslowe, super useful! I'm pretty sure we can work on this in a short time. I'll keep this issue updated

**Comment by mikouaj** [comment]
I was thinking about adding `-json` flag to achieve that.
Sth like `./gke-policy check --discovery -p gke-policy-demo -json` would produce only JSON to stdout (without out fancy info messages)

**Comment by rickygodoy** [comment]
@danielmarzini Are you working on this or I can assign to myself?

**Comment by danielmarzini** [comment]
Hey @rickygodoy thanks for asking, I'm blocked onto another task, ff to take this one. Thanks!

**Comment by rickygodoy** [comment]
Hello @scottslowe, it's implemented and can be used with `-json` flag:

Like so:
`./gke-policy check --project my-nice-project --location us-central1-c --name gke-1 -json`

**Comment by mikouaj** [comment]
@scottslowe we have created v1.2.2 release for you.
You can download the new version of a binary from the [v1.2.2 release page](https://github.com/google/gke-policy-automation/releases/tag/v1.2.2).
