### ISSUE TITLE
All policies skipped - no checks perfomed 

### ISSUE THREAD

**Issue by lukpep** [google/gke-policy-automation#163]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do
not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Debug Output

https://gist.github.com/lukpep/61f5d104e28186466a35cb532ea3033b

### Steps to Reproduce

clone the newest repo, build it and try to use gke policy automation with basic command:

```
./gke-policy check best-practices --project my-project-id --location europe-west1 --name my-cluster-name
```
The same thing happens (meaning nothing is checked) when used with config file and discovery options - clusters are found but no checks are performed - only logs about skipping policy test files from https://github.com/google/gke-policy-automation/blob/main/internal/policy/policy.go#L133

### Expected Behavior

checks are performed

### Actual Behavior
no checks are performed

**Comment by danielmarzini** [comment]
Hello @lukpep, thanks for reporting this one. Could you please tell me which version are you using? the main branch or a release? can you please test also the latest release?

**Comment by lukpep** [comment]
Hi @danielmarzini (small world by the way :D - thx for the anthos help)

Main branch at this commit: https://github.com/google/gke-policy-automation/commit/a2f8c69f8e9bcaa6ee8c0ffe3b83f15e1a57628d

**Comment by danielmarzini** [comment]
Hey @lukpep, indeed very small ;)

It should be ok now, could you please sync up with the main branch and tell me if everything is ok?

**Comment by lukpep** [comment]
yes - now it works - thanks :)
