### ISSUE TITLE
Cloud Storage output: add datetime prefix to objects

### ISSUE THREAD

**Issue by mikouaj** [google/gke-policy-automation#72]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do
not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Current Cloud Storage output always writes a single object with a configured given name and prefix.
Subsequent executions of a tool will overwrite existing file. In order to maintain history of a reports, the objects can be prefixed with a generated datetime i.e. `gke_report_20220516_2141.json` (YYYYMMDD_HHMM prefix). 

### References

N/A

**Comment by rickygodoy** [comment]
@mikouaj 
Do you think this should be the default behavior or come from a config (for instance, "prefix_date" config)?

**Comment by mikouaj** [comment]
@rickygodoy that's good idea. I would make it configurable but enabled by default, i.e.:

`addDatePrefix: true`  default
`addDatePrefix: false` <- if someone wants to disable this they need to add this option explicitly
